version: "3.8"

services:
  node:
    image: node:16-alpine3.12
    volumes: 
    - ./:/home/project
    working_dir: /home/project
    command: yarn start
    ports:
    - "8080:8080"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
    - "3306:3006"
    